### ISSUE TITLE
Performance regression in voyage calculator

### ISSUE THREAD

**Issue by marcelgcom** [stt-datacore/website#16]
The voyage calculator used to be quick on the default setting but now it can take up to a couple of minutes. This is not a huge issue but it might be worth an investigation in case this happens needlessly.

**Comment by AlexCPU** [comment]
The voyage calculator is a compiled WebAssembly (WASM), which runs completely locally on your device, and has not been changed since 21st March 2019 (see https://github.com/stt-datacore/website/commits/master/static/voymod.wasm).  Any change in performance will have to be related to the web browser or computer that you are using.  WebAssembly is supported on all modern desktop browsers, excluding Internet Explorer (see https://caniuse.com/?search=WASM).

Anecdotally we've heard of similar issues, but it's looking like it is something outside out control, so if you can try a different web browser, and/or computer that would be appreciated, it should work on almost anything with a web browser.

**Comment by AlexCPU** [comment]
After more testing, we've concluded this will most likely be related to the number of crew that you have, as our internal testing shows that users that were mentioning slow calculations went back to the performance they were used to when using an account with less crew on it.

Calculation speed is proportional to the number of crew to the power of the search depth.  On this basis @marcelgcom we would recommend dropping the search depth to 5, or possibly even 4.  The differences in optimisation should be very minimal.
