### ISSUE TITLE
Crew Retrieval - color of rarity stars

### ISSUE THREAD

**Issue by danardone** [stt-datacore/website#206]
Can you change the color of the stars to black if not owned and gold for number of fuses, please? 
Presently, it's confusing. 
The black stars (which one would think are not owned) are actually the number of stars owned. 
And the gray stars (which one would think are the number of stars needed) are actually the number already owned.
Thank you.

**Comment by AlexCPU** [comment]
When someone looks at this, it's not a specific issue on the crew retrieval page, we're using the same colours across the regular crew stats, and the player tools crew stats tabs.

There's an interesting question here around colour and the two different colour themes, as I think I agree with @danardone for the dark theme that the colours are confusing, whereas because we use the same on the light theme, they actually look pretty clear, and I fear the missing fuse levels in black on these could look worse.

The solution might just be swap the black star for a gold star.  Thoughts?

Examples:
![image](https://user-images.githubusercontent.com/4178651/114923064-4941ea80-9e24-11eb-9a32-d46a68f7f5a5.png)
![image](https://user-images.githubusercontent.com/4178651/114923112-55c64300-9e24-11eb-9049-9352fd46f3b8.png)

**Comment by AlexCPU** [comment]
Options:
goldenrod and black on the light theme:
![image](https://user-images.githubusercontent.com/4178651/114924347-cb7ede80-9e25-11eb-8d72-98dcc4329ca6.png)

goldenrod and black on the dark theme:
![image](https://user-images.githubusercontent.com/4178651/114924594-126cd400-9e26-11eb-99b0-38cab32b0f73.png)

goldenrod and existing grey on the light theme:
![image](https://user-images.githubusercontent.com/4178651/114924703-2fa1a280-9e26-11eb-8705-02403e4577c7.png)

goldenrod and existing grey on the dark theme:
![image](https://user-images.githubusercontent.com/4178651/114924898-5bbd2380-9e26-11eb-93e0-415e2d77bea6.png)

**Comment by AlexCPU** [comment]
We don't have to use the same colours of both themes, but I think personally I'm leaning in the direction of the light grey for both colour themes.

**Comment by danardone** [comment]
Hi.

Yes! 

This is what I was trying to convey. 

When I look at this I think the player has Constable Odo fully fused. 

But the player does not have Shinzon in their crew.

-DNard

**Comment by AlexCPU** [comment]
@danardone Please can you try out the changes proposed on this test instance? https://27a77ae1.website-i3mu.pages.dev/ 

(test instances miss some functionality such as sharing profile, and fleet data)
