### ISSUE TITLE
Import not working, proper validated json is truncated on paste.

### ISSUE THREAD

**Issue by venimus** [stt-datacore/website#207]
Weird import behavior with this data
[player.txt](https://github.com/stt-datacore/website/files/6320989/player.txt)
![image](https://user-images.githubusercontent.com/632282/114935293-af8a3580-9e43-11eb-954a-58e861bb3551.png)

I tried copy/paste multiple times with different browsers, also with "file upload", all failed.

**Comment by ussjohnjay** [comment]
Looks like this is another instance where the player data has been put into an array of objects instead of the expected single object. There does not seem to be an explanation for why this happens, but it does usually correct itself within a few minutes. If it happens to you again, please try refreshing the player data link and then copy-paste into DataCore again.

We'll try to update the player tools so that it can check for this problem in the future and deal with it accordingly. And thanks for sharing the JSON file, that's a big help!

**Comment by venimus** [comment]
I did refresh it several times but nothing changed. However after I started a voyage later and tried again, then it worked
