### ISSUE TITLE
Crew index page should show new crew first by default

### ISSUE THREAD

**Issue by ineffyble** [stt-datacore/website#211]
Will make the front page more interesting & relevant, and in many cases be useful to players who are visiting to look at the new crew.

Ironically because of how we do things, new crew appear on the last page, even though we don't offer sorting by release date. So perhaps all we have to do is reverse the order of the default/initial crew list.

**Comment by ussjohnjay** [comment]
I like this. But that might also mean we should add a pseudocolumn for sorting by "date added" or something like that. Because right now you can't actually go back to the default sort if you change to a different sort. (It's a bug of the new ability to remember your last form settings, though it's one I didn't think was worth addressing because the current default sort seemed useless to me anyway.)
