### ISSUE TITLE
Amanda Grayson and Amanda Rogers both have the Short Name "Amanda"

### ISSUE THREAD

**Issue by AdmiralMemo** [stt-datacore/website#23]
Title says it all. When I export the Crew Spreadsheet, both of these characters have the same Short Name, even though they're different characters.

**Comment by AlexCPU** [comment]
We pull the short name data (and all other data) directly out of the game, so this is defined by WRG rather than us, so unfortunately this is functioning exactly as designed/intended.

If you need to differentiate between them, the two Amanda Grayson's have the `amanda_greyson` trait, and Amanda Rogers has the `rogers_amanda` trait
