### ISSUE TITLE
Playertools broken

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/website#233]
We seem to have a bug that only affects Edge where it returns a blank page whilst processing player.json.
![image](https://user-images.githubusercontent.com/4178651/119489211-5e7b3480-bd53-11eb-8c1b-b1f41b1cd145.png)

**Comment by AlexCPU** [comment]
@ussjohnjay I think this might be coming from your voyage tools based on the errors?

**Comment by ussjohnjay** [comment]
Hmmm. I haven't been able to reproduce this on Edge (version 90.0.818.66). Tested player tools with about a dozen player.json files I have on hand and everything seems to work as expected. @AlexCPU do you still have the player file that triggered these errors?

@joshurtree Looking at the `renderCrew` method in your voyagestats component, the `CrewPopup` component is expecting a `crew` object formatted from `playerData`, not `voyageData`, which is why `imageUrlPortrait` isn't initially there and may be why the individual skill numbers don't line up exactly. Passing `playerData` as a prop down from playertools to voyagestats (and slightly rewriting renderCrew to get the needed crew properties from the playerData crew array instead) *might* fix the underlying issue here, though honestly I don't see any reason why what you've done here doesn't always work.

**Comment by AlexCPU** [comment]
@ussjohnjay there's an example player.json on #243 (which I've closed as a dupe of this) which seems to reliably cause the issue.  Can you have a look at that?

**Comment by mururoa** [comment]
This is different from #241 . Please reopen it.

**Comment by ineffyble** [comment]
This issue, which affected specific browsers and versions of browsers, should now be resolved.

**Comment by ineffyble** [comment]
@mururoa Can you confirm if your issue is still occurring or not?
