### ISSUE TITLE
parsing "ambiguous" cases in farm request

### ISSUE THREAD

**Issue by DocOnGitHub** [stt-datacore/website#28]
When submitting a _farm_ query for an item that has more than one variation in-game (i.e. 0 Hyperspanner) **datacore** currently returns "There are 2 items matching that: Hyperspanner, Hyperspanner. Which one did you mean?" If you then follow up with "Hyperspanner DS9" or "Hyperspanner ENT", you'll get the proper result, but I'd like to see a prompt added to inform the user of what the variations are without having to look them up elsewhere (i.e. the STT Wiki). If I run the same command in **got bot**, it returns: "2 items matches. Did you mean Hyperspanner (DS9), Hyperspanner (ENT)?"

To my understanding there are several of these "ambiguous" items in the game. The ones I know of are: Combadge, Communicator, Desktop Monitor (3 cases), Hypospray, Hyperspanner, Klingon Armor, Medical Scanner, Phaser Type 1/2/3, Starfleet Uniform (5 cases), Tricorder, Writing PADD (4 cases).

**Comment by ineffyble** [comment]
So it turns out that `Hyperspanner DS9` and `Hyperspanner ENT` don't actually return the proper result, they return a random result 🤨

I think I've got a better system worked out, about to make a pull request. Essentially it'll show you all the matches in more detail (including photo, which is best way to distinguish them), and include their unique "symbol" name, which you can use to select a specific item if there's multiple with identical name & rarity.

![image](https://user-images.githubusercontent.com/834880/104107740-d26fef80-5312-11eb-8257-daba05290604.png)
